### ISSUE TITLE
Changing the settings in the dashboard

### ISSUE THREAD

**Issue by Fonsey** [Tamfoolery/nodecg-follow#1]
Hey Ho!

For whatever reason, whenever I try to change the settings of the bundle via the dashboard it just crashes and doesn't save the settings.

I might just be doing something completely wronge because I'm pretty new to NodeCG but I'd still appreciate if you could help me out here <3

**Comment by DJ411** [comment]
I'm having the same issue with the settings "cog". I go to enter in my username and nothing shows up. I see in the files "giantwaffle" is already set. If his name is used as a working example i feel that when i go to change the settings in the dashboard it should show his name.

Click the cog and enter your settings.

**Comment by Tam** [comment]
Working on it (I may have forgotten to finish building this!)
