### ISSUE TITLE
Failed start up

### ISSUE THREAD

**Issue by DJ411** [Tamfoolery/nodecg-follow#2]
Having an issue running nodecg. Installed new 0.6.0 with a fresh install and this being the only bundle i'm using it doesn't run.

What am i missing. Using Git Bash to run "node index.js"

![ss 2015-07-06 at 08 45 11](https://cloud.githubusercontent.com/assets/609616/8536483/f48da94a-241f-11e5-8f84-4fa71b975507.png)

**Comment by 1fyme** [comment]
Python may not be installed. I encountered this problem today, and downloaded Python version 2.7.10 for Window:. https://www.python.org/downloads/

**Comment by Tam** [comment]
As @ofs114 said, it does look like an issue with python not being installed. You'll need [Python 2.7.10](https://www.python.org/downloads/) (or higher, but not 3) installed for some nodecg/nodecg-follow dependencies to work.

**Comment by DJ411** [comment]
Thanks. Its working now. I also didn't have Visual studio installed. installing both might have helped idk.
